modLoader="neoforge"
loaderVersion="[21,)"
license="Apache-2.0"

[[mods]]
modId="roadencounters"
version="${file.jarVersion}"
displayName="Road Encounters"
description="Dynamic encounters along RoadArchitect paths (ambushes, etc.)"

[[dependencies.roadencounters]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.roadencounters]]
modId="neoforge"
mandatory=true
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.roadencounters]]
modId="roadarchitect"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
