modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/0xCoDSnet/RoadArchitect-Road-Encounters/issues"
license="${mod_license}"

[[mods]]
modId="roadencounters"
version="${version}"
displayName="${mod_name}"
description="${mod_description}"
logoFile = "assets/roadarchitect/icon.png"
displayURL="https://github.com/0xCoDSnet/RoadArchitect-Road-Encounters"

[[dependencies.roadencounters]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadencounters]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadencounters]]
modId="roadarchitect"
type = "required"
versionRange="*"
ordering="NONE"
side="BOTH"
