modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/0xCoDSnet/RoadArchitect-Road-Encounters/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description="${mod_description}"
logoFile = "assets/roadarchitect_roadencounters/icon.png"
displayURL="https://github.com/0xCoDSnet/RoadArchitect-Road-Encounters"
authors = "${mod_authors}"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="roadarchitect"
type = "required"
versionRange="[1.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_config_version},)"
ordering = "NONE"
side = "BOTH"

[modproperties.${mod_id}]
catalogueImageIcon = "assets/roadarchitect_roadencounters/icon.png"

